### DISCUSSION TITLE
docker for dummies

### DISCUSSION THREAD

**Discussion by plex3r** [fabXlabs/fabX#463] [Q&A] [answered]
Hi,

I'm looking for a tool access system for our Hackspace and this seems to be one of the good ones but docker isn't really my strong point.

Can you provide some more explicit instructions on setting this up on a local server.

I looked at the docker-compose file but while I ended up with 2 containers the postgres one didn't start due to no superuser password set.

Thanks

**Comment by sschmitt98** [comment, marked as answer]
Hi,

can you try the following compose file? Copy & paste it into a file called `docker-compose.yml`:

```yaml
services:
  app:
    image: ghcr.io/fabxlabs/fabx:0.0.927
    restart: always
    ports:
      - "8000:1234"
    environment:
      PORT: 1234
      FABX_DB_URL: jdbc:postgresql://postgres/postgres
      FABX_DB_USER: postgres
      FABX_DB_PASSWORD: postgrespassword

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db:
```

First, run `docker compose up postgres` in the same directory, to start the database (for older versions of Docker the command is `docker-compose` instead of `docker compose`, note the `-`). Wait a bit until it outputs a log line like this:

```
2023-12-10 17:36:55.848 UTC [1] LOG:  database system is ready to accept connections
```

Then, open a second terminal in the same directory and run `docker compose up app` to start the actual app. It should log a few different lines until it logs:

```
2023-12-10 17:39:24,340 INFO  [DefaultDispatcher-worker-1] Application: Responding at http://0.0.0.0:1234
```

Now, the app should be available at port 8000, i.e., open a browser on the same machine at `http://localhost:8000` (or `http://127.0.0.1:8000`). From then, you should be able to follow https://github.com/fabXlabs/fabX#setup--documentation

The differences to the compose file in the repository are:
* it is reduced to the minimum of containers you need: the PostgreSQL database and the app itself
* for the app it uses the prebuilt image  available at https://github.com/fabXlabs/fabX/pkgs/container/fabx
* For the database it defines a volume. The database stores its data in this volume and the volume has an independent lifecycle of the containers. Without the volume, the data would be lost when the database container is stopped (e.g. for updates).

Some general notes on Docker:
* You can check the running containers with `docker ps`
* You can list all containers (including the stopped ones) with `docker ps -a`
* You can stop a container with `docker stop <container name>`
* You can delete a stopped container with `docker rm <container name>`
* You can start a "compose" in the background with `docker compose up -d` (`d` being short for "detached")
* You can stop a "compose" with `docker compose down`
* You can stop a "compose" and delete all volumes defined in it with `docker compose down --volumes`

If this does not work, can you either copy & paste the commands and the output or upload a screenshot of it?

Thank you for trying fabX!
